### ISSUE TITLE
 In PackageManifest.php line 120:

### ISSUE THREAD

**Issue by dbrax** [LaravelDaily/ExpenseManager#3]
Just after i runned composer install they i try to perform php artisan key:generate i ended up getting this 

In PackageManifest.php line 120:

  Undefined index: name

php 7.4

@PovilasKorop

**Comment by PovilasKorop** [comment]
@dbrax this project is on Laravel 5.5 and no changes made since then, so it likely wouldn't work on newer PHP versions

**Comment by dbrax** [comment]
Got it  i have just seen this https://github.com/LaravelDaily/QuickAdminPanel-ExpenseManager
